# Generated by Django 5.0.6 on 2024-05-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_networkmember_product_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkmember',
            name='product_model',
        ),
        migrations.RemoveField(
            model_name='networkmember',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='networkmember',
            name='product_release_date',
        ),
    ]
